### ISSUE TITLE
Scrolling doesn't work

### ISSUE THREAD

**Issue by alexander-heimbuch** [rse/blessed-xterm#1]
First of all I really like to thank you for the nice extension to blessed. It really saved time for my little [command line tool](https://www.npmjs.com/package/concurrently-dashboard) and it's working well so far.

The only problem I have is that I'm not able to scroll in the CLI output. My configuration is as follows:

```
const blessed = require('blessed')
const XTerm = require('blessed-xterm')

const screen = blessed.screen({
  smartCSR: true,
  dockBorders: false,
  fullUnicode: true,
  autoPadding: true
})

const addTerminal = (label = '', top = 0, height = 100) => {
  const terminal = new XTerm({
    label,
    top,
    height,
    width: screen.width,
    shell: process.env.SHELL || 'sh',
    args: [],
    cursorType: 'block',
    scrollback: 1000,
    border: {
      type: 'line'
    },
    style: {
      border: {
        fg: '#0f0'
      }
    },
    padding: 1
  })

  screen.append(terminal)

  return terminal
}
```

**Comment by rse** [comment]
Well, blessed-xterm does not scroll just by itself. You have to programmatically drive its scrolling. I've added an example to sample.js now.
