### ISSUE TITLE
windows-build-tools

### ISSUE THREAD

**Issue by binarymist** [rse/blessed-xterm#5]
Could be worth updating the [Installation](https://github.com/rse/blessed-xterm#installation) section to [include](https://github.com/Microsoft/node-pty#dependencies-on-windows) `windows-build-tools` `global`y as either a replacement to installing the (last time I used) bloated MS Visual C/C++, or as an alternative.

**Comment by binarymist** [comment]
Probably should also mention the linux build tools required, as they are often not installed by default (just tried on Mint).

**Comment by rse** [comment]
The windows-build-tools are already mentioned today in the README under Installation.
