### ISSUE TITLE
do not override users TERM env setting

### ISSUE THREAD

**Issue by higginsrob** [rse/blessed-xterm#6]
https://github.com/rse/blessed-xterm/blob/b81d27fdbb3a88747690f8b306d695cb97352d3d/blessed-xterm.js#L497

this  
`env = Object.assign({}, env || this.options.env || process.env)`
or
`env = Object.assign({ TERM: "xterm" }, env || this.options.env || process.env)`
might be better.

currently there's no way to set xterm-256color

**Comment by rse** [comment]
Code now changed. It now allows TERM to be set to xterm or xterm-XXX.
